config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  
  resources :companies do
    member do
      get :company_ticket
    end
    collection do
      post '/generate_bill' => 'companies#generate_bill', :as => 'generate_bill'
    end
  end
  # map.resources :companies, :collection => { :generate_bill => :post }

  resources :tickets 
  # do
  #   member do
  #     get :generate_bill
  #   end
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :tickets, dependent: :destroy

  def formatted_name
    "#{name} - #{branch}"
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :company_ticket]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def company_ticket
    @company_tickets = @company.tickets.paginate(page: params[:page], per_page: 5)
  end

  def generate_bill
    if params[:ticket_ids].present?
      bill_service = BillingService.new params[:ticket_ids]
      bill_service.generate_and_send_bill
    else 
      redirect_back(fallback_location: root_path, notice: "No tickets selected")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :branch)
    end
  end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:dob, :doj, :passenger_name, :from, :to, :travel_class, :ticket_amount, :agent_charge, :cgst, :sgst, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch, id: :company_branch %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/company_ticket.html.erb
<style type="text/css">
  table, th, td {
    border: 1px solid black;
  }

  th, td {
    padding: 15px;
  }
</style>

<!-- <script>
  function myFunction() {
    var arr = [];
    var x = document.getElementsByClassName("selection");    
    for(var i = 0; i < x.length; i++){
      if(x[i].checked){
        arr[i] = x[i].value;
      }
    }
    alert("Generating bill for following: " + arr);
    document.
    // return arr;
    // jQuery.ajax({
    //   type: "GET",
    //   url: "/companies/generate_bill",
    //   data: { ticket_ids: 1}
    // });
  }
</script>
-->

<h1>Tickets</h1>
<%= form_tag(generate_bill_companies_path, method: 'post') do %>
  <table style="margin-left: auto; margin-right: auto;">
    <thead>
      <tr>
        <th>D/O Booking</th>
        <th>D/O Journey</th>
        <th>Passenger name</th>
        <th>From</th>
        <th>To</th>
        <th>Class</th>
        <th>Ticket Amount</th>
        <th>Agent Charge</th>
        <th>CGST</th>
        <th>SGST</th>
        <th>Company</th>
        <th colspan="3">Actions</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
      <% @company_tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.dob %></td>
        <td><%= ticket.doj %></td>
        <td><%= ticket.passenger_name %></td>
        <td><%= ticket.from %></td>
        <td><%= ticket.to %></td>
        <td><%= ticket.travel_class %></td>
        <td><%= ticket.ticket_amount %></td>
        <td><%= ticket.agent_charge %></td>
        <td><%= ticket.cgst %></td>
        <td><%= ticket.sgst %></td>
        <td><%= link_to ticket.company.formatted_name , company_path(ticket.company) %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= check_box_tag 'ticket_ids[]', ticket.id %>          
        </td>
      </tr>    
      <% end %>
    </tbody>
  </table><br>
  <%= submit_tag "Generate Bill" %>
<% end %>
<%= will_paginate @company_tickets %>
<br>
<button><%= link_to 'New Ticket', new_ticket_path %></button><br><br>
<%# if company.tickets.count > 0 %>
<!-- <button onclick="myFunction()" >Generate Bill<%#= render 'generate_bill' %></button> -->
<%# end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/generate_bill.html.erb
<p>Generating Bill for:</p>
<table style="margin-left: auto; margin-right: auto;">
  <% Ticket.find(params[:ticket_ids]).each do |ticket| %>
  <tr>
    <td><%= ticket.dob %></td>
    <td><%= ticket.doj %></td>
    <td><%= ticket.passenger_name %></td>
    <td><%= ticket.from %></td>
    <td><%= ticket.to %></td>
    <td><%= ticket.travel_class %></td>
    <td><%= ticket.ticket_amount %></td>
    <td><%= ticket.agent_charge %></td>
    <td><%= ticket.cgst %></td>
    <td><%= ticket.sgst %></td>
    <td><%= ticket.company.formatted_name %></td>
  </tr>
  <% end %>
</table>
<p>Please check your inbox attachment for the bill.</p>

app/views/companies/index.html.erb
<style type="text/css">
  table, th, td {
    border: 1px solid black;
  }

  th, td {
    padding: 15px;
  }
</style>

<h1>Companies</h1>

<table style="margin-left: auto; margin-right: auto;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Branch</th>
      <th colspan="3">Actions</th>
      <th>Tickets</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.branch %></td>
      <td><%= link_to 'Show', company %></td>
      <td><%= link_to 'Edit', edit_company_path(company) %></td>
      <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to "All Tickets", company_ticket_company_path(company) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @companies %>
<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @company.branch %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_footer.html.erb
<style>
footer {
  text-align: center;
  background-color: #333;
  color: #f2f2f2;
  display: block;
  margin-top: 250px;
}
</style>

<footer>
  <p>Author: Priya Hinduja<br>
  <a href="mailto:priyahinduja15@gmail.com">priyahinduja15@gmail.com</a></p>
</footer>

app/views/layouts/_header.html.erb
<style type="text/css">
  /* Add a black background color to the top navigation */
  #topnav {
    background-color: #333;
    overflow: hidden;
  }

  /* Style the links inside the navigation bar */
  #topnav button {
    float: left;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  /* Change the color of links on hover */
  /*.active, .btn:hover {
    background-color: #ddd;
    color: black;
  }*/

  /* Add a color to the active/current link */
  #topnav button.btn {
    background-color: #4CAF50;
    color: white;
  }
</style>
<body>
  <div id="topnav">
    <button class="btn"><%= link_to 'Companies', companies_path %></button>
    <button class="btn"><%= link_to 'Tickets', tickets_path %></button>
    <!-- <button>Bills</button> -->
    <!-- <button>About</button> -->
  </div>

 <!--  <script>
    // Add active class to the current button (highlight it)
    var header = document.getElementById("topnav");
    var btns = header.getElementsByClassName("btn");
    for (var i = 0; i < btns.length; i++) {
      btns[i].addEventListener("click", function() {
        var current = document.getElementsByClassName("active");
        current[0].className = current[0].className.replace(" active", "");
        this.className += " active";
      });
    }
  </script> -->

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HTC</title>
    <link rel = "icon" href = "download.png" type = "image/x-icon">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style="text-align:center; vertical-align:middle;">
    <!-- style="text-align:center; vertical-align:middle; background-image: url(download.png); background-repeat: no-repeat; background-position: bottom;" -->
    <%= render 'layouts/header'%>
    <br>
    <% flash.each do |type, msg| %>
      <div id="notice">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_field :dob, id: :ticket_dob %>
  </div>

  <div class="field">
    <%= form.label :doj %>
    <%= form.date_field :doj, id: :ticket_doj %>
  </div>

  <div class="field">
    <%= form.label :passenger_name %>
    <%= form.text_field :passenger_name, id: :ticket_passenger_name %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from, id: :ticket_from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to, id: :ticket_to %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.text_field :travel_class, id: :ticket_travel_class %>
  </div>

  <div class="field">
    <%= form.label :ticket_amount %>
    <%= form.text_field :ticket_amount, id: :ticket_amount %>
  </div>

  <div class="field">
    <%= form.label :agent_charge %>
    <%= form.text_field :agent_charge, id: :ticket_agent_charge %>
  </div>

  <div class="field">
    <%= form.label :cgst %>
    <%= form.text_field :cgst, id: :ticket_cgst %>
  </div>

  <div class="field">
    <%= form.label :sgst %>
    <%= form.text_field :sgst, id: :ticket_sgst %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.collection_select :company_id, Company.order(:name), :id, :formatted_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<style type="text/css">
  table, th, td {
    border: 1px solid black;
  }

  th, td {
    padding: 15px;
  }
</style>


<h1>Tickets</h1>

<table style="margin-left: auto; margin-right: auto;">
  <thead>
    <tr>
      <th>D/O Booking</th>
      <th>D/O Journey</th>
      <th>Passenger name</th>
      <th>From</th>
      <th>To</th>
      <th>Class</th>
      <th>Ticket Amount</th>
      <th>Agent Charge</th>
      <th>CGST</th>
      <th>SGST</th>
      <th>Company</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.dob%></td>
        <td><%= ticket.doj%></td>
        <td><%= ticket.passenger_name %></td>
        <td><%= ticket.from %></td>
        <td><%= ticket.to %></td>
        <td><%= ticket.travel_class %></td>
        <td><%= ticket.ticket_amount %></td>
        <td><%= ticket.agent_charge %></td>
        <td><%= ticket.cgst %></td>
        <td><%= ticket.sgst %></td>
        <td><%= link_to ticket.company.formatted_name , company_path(ticket.company) %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @tickets %>
<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>
<%#= link_to 'Back', company_ticket_company_path(company) %>

app/views/tickets/show.html.erb
<p>
  <strong>D/O Booking:</strong>
  <%= @ticket.dob %>
</p>

<p>
  <strong>D/O Journey:</strong>
  <%= @ticket.doj %>
</p>

<p>
  <strong>Passenger name:</strong>
  <%= @ticket.passenger_name %>
</p>

<p>
  <strong>From:</strong>
  <%= @ticket.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @ticket.to %>
</p>

<p>
  <strong>Class:</strong>
  <%= @ticket.travel_class %>
</p>

<p>
  <strong>Ticket Amount:</strong>
  <%= @ticket.ticket_amount %>
</p>

<p>
  <strong>Agent Charge:</strong>
  <%= @ticket.agent_charge %>
</p>

<p>
  <strong>CGST:</strong>
  <%= @ticket.cgst %>
</p>

<p>
  <strong>SGST:</strong>
  <%= @ticket.sgst %>
</p>

<p>
  <strong>Company:</strong>
  <%= @ticket.company.name %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', company_ticket_company_path(@ticket.company) %>